Use tket 2D qubit indices with new register name
quantumlib/ReCirq pull request #120
Opened 2021-01-07 11:17 UTC by ss2165

Previously it seems 2D registers (as the equivalent of `GridQubit`) were used with "q" as the register name, which lead to failure as "q" is a reserved name in tket for the default 1D register (this should be made more clear in the tket docs/error message). I have changed the name to "grid", and removed the workaround used to map 1D indices to 2D qubits.

2021-01-07 21:29 UTC, mpharrigan commented
Thanks for the patch. I will take a closer look shortly. I'm trying to remember what motivated this originally. It must have been the "q" undocumented failure. 

Do you want to also patch `recirq.qaoa` code to use 2d registers as well?

2021-01-11 11:39 UTC, ss2165 commented
Thanks, I've replicated the patch in `recirq.qaoa.placement` now, is there anywhere else I should to edit?

2021-01-13 01:04 UTC, mpharrigan requested changes
Thanks again! This really cleans things up. Left a couple comments

2021-01-13 01:04 UTC, mpharrigan commented on docs/qaoa/routing_with_tket.ipynb
> +        "    return cirq.LineQubit(ind[0]) if len(ind) == 1 else cirq.GridQid(*ind, dimension=len(ind))\n",
the `dimension` argument being equal to `len(ind)` is a coincidence and should be omitted. This is to support qudits. Just use `cirq.GridQubit`.

2021-01-13 01:04 UTC, mpharrigan commented on recirq/qaoa/placement.py
> +        else cirq.GridQid(*ind, dimension=len(ind))
ditto, use `cirq.GridQubit` and omit `dimension`.

2021-01-18 14:25 UTC, ss2165 commented
Thank you for the comments, I've made the suggested changes. I must confess I actually misread `GridQid` as `GridQubit`...

2021-01-20 23:08 UTC, mpharrigan approved these changes
Thanks!

2021-01-20 23:09 UTC, merged