Use new cirq transformer API for quantum_chess
quantumlib/ReCirq pull request #276
Opened 2022-03-29 13:01 UTC by dstrain115

- Convert CircuitTransformer to use __call__ to conform to Transformers
  API.
- Convert SycamoreDecomposer to a free function that conforms to
  Transformers API.

2022-04-13 17:59 UTC, tanujkhattar requested changes
Looking good overall. Main comment is around using Cirq's inbuilt transformers for compiling circuits to sqrt iswap target gateset, instead of the custom-written transformer here.

2022-04-13 17:59 UTC, tanujkhattar commented on recirq/quantum_chess/circuit_transformer.py
> +    ) -> cirq.Circuit:
I think we can get rid of the `CircuitTransformer` interface now and simply decorate the derived classes with `@cirq.transformer` decorator -- this decorator will verify the that the derived classes adhere to `cirq.TRANSFORMER` interface and also add useful features like automated logging.

2022-04-13 17:59 UTC, tanujkhattar commented on recirq/quantum_chess/circuit_transformer.py
> +        circuit: "cirq.AbstractCircuit",
```suggestion
        circuit: cirq.AbstractCircuit,
```

2022-04-13 17:59 UTC, tanujkhattar commented on recirq/quantum_chess/circuit_transformer.py
> +        circuit: "cirq.AbstractCircuit",
```suggestion
        circuit: cirq.AbstractCircuit,
```

2022-04-13 17:59 UTC, tanujkhattar commented on recirq/quantum_chess/circuit_transformer.py
> +    def __call__(
Decorate the class with `@cirq.transformer` to add support for automated logging

2022-04-13 17:59 UTC, tanujkhattar commented on recirq/quantum_chess/circuit_transformer.py
> +    def __call__(
Decorate the class with `@cirq.transformer` to add support for automated logging

2022-04-13 17:59 UTC, tanujkhattar commented on recirq/quantum_chess/circuit_transformer.py
> +        circuit: "cirq.AbstractCircuit",
```suggestion
        circuit: cirq.AbstractCircuit,
```

2022-04-13 17:59 UTC, tanujkhattar commented on recirq/quantum_chess/circuit_transformer.py
> +        circuit: "cirq.AbstractCircuit",
```suggestion
        circuit: cirq.AbstractCircuit,
```
```suggestion
        circuit: "cirq.AbstractCircuit",
```

2022-04-13 17:59 UTC, tanujkhattar commented on recirq/quantum_chess/circuit_transformer.py
> +def decompose_into_sqrt_iswap(
This entire transformer can now be replaced by a single function call in Cirq:
```python
cirq.optimize_for_target_gateset(
    circuit, gateset=cirq.SqrtIswapTargetGateset(), context=cirq.TransformerContext(deep=True)
)
```

As an evidence, here is a colab which tests compilation of all the different cases hardcoded in the `transform_op_into_sqrt_iswap` method above:

https://colab.research.google.com/drive/1sjacBgm1oqa2giTQ_QUlu_GxKqJ9GLsR?resourcekey=0-UIKWzHrpTw58dWE-VPnqlw&usp=sharing

2022-04-13 17:59 UTC, tanujkhattar commented on recirq/quantum_chess/circuit_transformer.py
> +def decompose_into_sqrt_iswap(
This entire transformer can now be replaced by a single function call in Cirq:
```python
cirq.optimize_for_target_gateset(circuit, gateset=cirq.SqrtIswapTargetGateset(), ignore_failures=False)
```

As an evidence, here is a colab which tests compilation of all the different cases hardcoded in the `transform_op_into_sqrt_iswap` method above:

https://colab.research.google.com/drive/1sjacBgm1oqa2giTQ_QUlu_GxKqJ9GLsR?resourcekey=0-UIKWzHrpTw58dWE-VPnqlw&usp=sharing

2022-05-03 23:10 UTC, closed without merging

2022-05-03 23:10 UTC, dstrain115 commented
Moved this to unitary repo.