So long, and thanks for all the fish!
quantumlib/ReCirq pull request #300
Opened 2022-06-16 13:52 UTC by cognigami

Quantum Chess' move to //unitary is complete.

2022-06-16 13:53 UTC, cognigami commented
By way of heads-up: I didn't have rights to remove the two references to quantum chess in .github/workflows:
 - black.yml
 -  pythonpackage.yml

2022-06-16 17:00 UTC, dstrain115 commented
Those two files are in the repository, so you should be able to edit them and submit them as part of the PR.
https://github.com/quantumlib/ReCirq/tree/master/.github/workflows

What permission errors are you seeing?

2022-06-16 17:07 UTC, mpharrigan commented
Woot! Maybe we should leave the `recirq/quantum_chess` directory with a README pointing to the new location. We can also have an `__init__.py` that raises an `ImportError` telling you to use the new package

2022-06-16 18:01 UTC, cognigami commented
Thanks @dstrain115, my token didn't have workflow permissions. I've pushed the commit now. Just waiting on advice on merging then patching PR #298 in to this PR.

2022-06-16 20:18 UTC, mpharrigan requested changes

2022-06-16 20:18 UTC, mpharrigan commented on .github/workflows/pythonpackage.yml
> -          RECIRQ_CHESS_TEST_SEED=789 RECIRQ_IMPORT_FAILSAFE=y pytest -v
this disables pytest for the whole package. remove the chess_test_seed but we still need the call to `pytest`

2022-06-16 20:19 UTC, mpharrigan commented
@cognigami what do you think about my suggestion:

> Maybe we should leave the recirq/quantum_chess directory with a README pointing to the new location. We can also have an __init__.py that raises an ImportError telling you to use the new package

2022-06-21 22:31 UTC, mpharrigan commented on quantum_chess/__init__.py
> +raise ImportError
you need to `raise ImportError()` so it actually constructs the exception object.

You can also add a helpful message: `raise ImportError("quantum_chess moved to github.com/quantumlib/unitary/")`

2022-06-21 22:31 UTC, mpharrigan commented on .github/workflows/pythonpackage.yml
> -          RECIRQ_CHESS_TEST_SEED=789 RECIRQ_IMPORT_FAILSAFE=y pytest -v
@cognigami this is an important issue to fix before merge ^

2022-06-22 17:07 UTC, mpharrigan commented on .github/workflows/pythonpackage.yml
> -          RECIRQ_CHESS_TEST_SEED=789 RECIRQ_IMPORT_FAILSAFE=y pytest -v
still missing call to `pytest`

2022-06-22 17:08 UTC, mpharrigan commented on quantum_chess/__init__.py
> +raise ImportError("quantum_chess moved to https://github.com/quantumlib/unitary/tree/main/unitary/quantum_chess")
this should be under `recirq/quantum_chess` where the previous `__init__.py` file was

2022-06-22 17:08 UTC, mpharrigan commented on quantum_chess/README.md
> +Quantum Chess has graduated to its own repository. You can follow the work on
this should move to `recirq/quantum_chess` where the code used to be

2022-06-24 16:07 UTC, mpharrigan requested changes
we need to still have the tests enabled for the rest of the repository

2022-06-24 16:07 UTC, mpharrigan commented on .github/workflows/pythonpackage.yml
> -          RECIRQ_CHESS_TEST_SEED=789 RECIRQ_IMPORT_FAILSAFE=y pytest -v
this is a call to `pytest` (don't be confused by the preceding environment variable declarations). We cannot have this removed. It tests the whole repository.

2022-06-24 16:07 UTC, mpharrigan commented on .github/workflows/pythonpackage.yml
> +
```suggestion
          # RECIRQ_IMPORT_FAILSAFE: skip tests on unsupported Cirq configurations
          RECIRQ_IMPORT_FAILSAFE=y pytest -v
```

2022-06-24 16:08 UTC, mpharrigan commented on docs/_toc.yaml
> -  path: /cirq/experiments/benchmarks/rabi_oscillations
bad merge?

2022-06-24 16:09 UTC, mpharrigan commented
This seems to revert the changes from #305 ?

2022-06-27 14:29 UTC, cognigami commented
I think I made a bad merge. Let's see if I can say the right prayers to the git gods to undo this.

2022-06-27 22:26 UTC, mpharrigan approved these changes

2022-06-27 22:26 UTC, merged