Hfvqe tutorials
quantumlib/ReCirq pull request #80
Opened 2020-10-16 23:48 UTC by ncrubin

2020-10-21 19:43 UTC, mpharrigan requested changes

2020-10-21 19:43 UTC, mpharrigan commented on docs/hfvqe/Making MolecularData.ipynb
> +    "# Making Molecule Files for HFVQE\n",
can you name this file in `lower_snake_case` with no spaces

2020-10-21 19:43 UTC, mpharrigan commented on docs/hfvqe/Making MolecularData.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAATYAAAD4CAYAAABmKcrZAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8vihELAAAACXBIWXMAAAsTAAALEwEAmpwYAAATWElEQVR4nO3
Can we commit this without outputs? At least to get git to realize this is a rename and not a wholesale deletion and addition

2020-10-21 19:45 UTC, mpharrigan commented
There's also the "odd qubit" example notebook still in the hfvqe module. What do you want to do with that?

2020-10-21 20:01 UTC, mpharrigan commented
Discussed offline: the hfvqe readme should be ported to docs/hfvqe/index.md to serve as a "landing page"

2020-10-23 01:41 UTC, ncrubin commented
@mpharrigan I see master already had the odd qubit tutorial. I was going to leave it in hfvqe since it doesn't add much to the example.  I will open another PR to remove.

2020-10-26 18:35 UTC, ncrubin commented
@mpharrigan let me know if I need to make any other structural changes.

2020-10-28 00:03 UTC, mpharrigan approved these changes

2020-10-28 00:03 UTC, merged